#!/usr/bin/env bash

# Group common used fzf configurations
fzf --height 50% --min-height 20 --border \
  --bind "ctrl-/:change-preview-window(down|hidden|)" \
  --bind "alt-up:preview-page-up,alt-down:preview-page-down" \
  --bind "ctrl-s:toggle-sort" \
  --header 'Press CTRL-/ to toggle preview' \
    "$@"