#!/usr/bin/env bash

# Checkout to a different branch

# Check git repository
git rev-parse HEAD > /dev/null 2>&1 || return

INITIAL_QUERY="${*:-}"

git branch -a --color=always | grep -v '/HEAD\s' | sort |
fzf \
  --min-height 20 --border \
  -m --ansi --nth 2..,.. \
  --bind "ctrl-/:change-preview-window(down|hidden|),alt-up:preview-page-up,alt-down:preview-page-down,ctrl-s:toggle-sort" \
  --ansi --multi --tac --preview-window right:70% \
  --query "$INITIAL_QUERY" \
  --preview '
    git log --oneline --graph --date=short --color=always --pretty="format:%C(auto)%cd %h%d %s" $(sed s/^..// <<< {} |
      cut -d" " -f1)' |
sed 's/^..//' | cut -d' ' -f1 |
sed 's#^remotes/##'


if [ -n "$selection" ]; then
  git checkout "${selection//origin\//}"
fi
