#!/usr/bin/env bash

# This function uses an additional package called 'jq'
# Select a command to run with 'npm run'
if ! [ -f package.json ]; then
  echo "No package.json in dir $(pwd)"
  return 1
fi

if command -v "jq" &> /dev/null; then
  echo "Dependency jq not found. Please install before running."
  return 1
fi

query="${*}"
selection="$(cat package.json |
  jq -r '.scripts | keys[]' |
  sort |
  fzf --query "$query" --height 50% --min-height 20 --border)"

if [ -z "$selection" ]; then
  exit 1
fi

npm run "$selection"
