#!/usr/bin/env bash

# Select a file and open it in your default editor
location="${1:-$HOME}"
query="${@:3}"
pattern="."
editor="${EDITOR:-vim}"

if ! [ -d "$location" ]; then
  pattern="$location"
  location="$HOME"
fi

selection=$(fd -L -tf "$pattern" "$location" |
  fzf --height 50% --min-height 20 --border \
    --bind ctrl-/:toggle-preview,alt-up:preview-page-up,alt-down:preview-page-down \
    --header 'Press CTRL-/ to toggle preview' \
    --multi \
    --preview "bat --color=always --style=numbers {}" \
    --header "(ctrl-/) Search in: $location" \
    --query "$query")

if [ -z "$selection" ]; then
  exit
fi

if [ -n "$2" ] && [ "$2" != "-" ]; then
  editor="$2"
fi

$editor "${selection[@]}"
