#!/usr/bin/env bash

# Regex to match a version in MAJOR, MINOR, and PATCH format
version_regex='.*version.*([0-9]+\.[0-9]+\.[0-9]+)".*'

file="${1:-package.json}"

rg "$version_regex" "$file" -r '$1' --no-line-number
